var searchData=
[
  ['savenode',['SaveNode',['../classglow_1_1_save_node.html',1,'glow']]],
  ['savenodeimporter',['SaveNodeImporter',['../class_save_node_importer.html',1,'']]],
  ['scalartraits_3c_20floatwrapper_20_3e',['ScalarTraits&lt; FloatWrapper &gt;',['../structllvm_1_1yaml_1_1_scalar_traits_3_01_float_wrapper_01_4.html',1,'llvm::yaml']]],
  ['scatterdatainst',['ScatterDataInst',['../classglow_1_1_scatter_data_inst.html',1,'glow']]],
  ['scatterdatanode',['ScatterDataNode',['../classglow_1_1_scatter_data_node.html',1,'glow']]],
  ['scheduler',['Scheduler',['../classglow_1_1_scheduler.html',1,'glow']]],
  ['scopedlogblock',['ScopedLogBlock',['../classglow_1_1_scoped_log_block.html',1,'glow']]],
  ['scopedtraceblock',['ScopedTraceBlock',['../classglow_1_1_scoped_trace_block.html',1,'glow']]],
  ['segment',['Segment',['../classglow_1_1_segment.html',1,'glow']]],
  ['selectnode',['SelectNode',['../classglow_1_1_select_node.html',1,'glow']]],
  ['selectnodeimporter',['SelectNodeImporter',['../class_select_node_importer.html',1,'']]],
  ['sgdnode',['SGDNode',['../classglow_1_1_s_g_d_node.html',1,'glow']]],
  ['shapehw',['ShapeHW',['../structglow_1_1_shape_h_w.html',1,'glow']]],
  ['shapehwd',['ShapeHWD',['../structglow_1_1_shape_h_w_d.html',1,'glow']]],
  ['shapenchw',['ShapeNCHW',['../structglow_1_1_shape_n_c_h_w.html',1,'glow']]],
  ['shapenhwc',['ShapeNHWC',['../structglow_1_1_shape_n_h_w_c.html',1,'glow']]],
  ['shapenhwdc',['ShapeNHWDC',['../structglow_1_1_shape_n_h_w_d_c.html',1,'glow']]],
  ['sigmoidcrossentropywithlogitsnode',['SigmoidCrossEntropyWithLogitsNode',['../classglow_1_1_sigmoid_cross_entropy_with_logits_node.html',1,'glow']]],
  ['sigmoidgradnode',['SigmoidGradNode',['../classglow_1_1_sigmoid_grad_node.html',1,'glow']]],
  ['sigmoidinst',['SigmoidInst',['../classglow_1_1_sigmoid_inst.html',1,'glow']]],
  ['sigmoidnode',['SigmoidNode',['../classglow_1_1_sigmoid_node.html',1,'glow']]],
  ['sigmoidnodeimporter',['SigmoidNodeImporter',['../class_sigmoid_node_importer.html',1,'']]],
  ['simplify_5ftype_3c_20const_20glow_3a_3anodehandle_20_3e',['simplify_type&lt; const glow::NodeHandle &gt;',['../structllvm_1_1simplify__type_3_01const_01glow_1_1_node_handle_01_4.html',1,'llvm']]],
  ['simplify_5ftype_3c_20const_20glow_3a_3anodevalue_20_3e',['simplify_type&lt; const glow::NodeValue &gt;',['../structllvm_1_1simplify__type_3_01const_01glow_1_1_node_value_01_4.html',1,'llvm']]],
  ['simplify_5ftype_3c_20glow_3a_3anodehandle_20_3e',['simplify_type&lt; glow::NodeHandle &gt;',['../structllvm_1_1simplify__type_3_01glow_1_1_node_handle_01_4.html',1,'llvm']]],
  ['simplify_5ftype_3c_20glow_3a_3anodevalue_20_3e',['simplify_type&lt; glow::NodeValue &gt;',['../structllvm_1_1simplify__type_3_01glow_1_1_node_value_01_4.html',1,'llvm']]],
  ['slicenode',['SliceNode',['../classglow_1_1_slice_node.html',1,'glow']]],
  ['slicenodeimporter',['SliceNodeImporter',['../class_slice_node_importer.html',1,'']]],
  ['slwsnodeimporter',['SLWSNodeImporter',['../class_s_l_w_s_node_importer.html',1,'']]],
  ['softmaxgradinst',['SoftMaxGradInst',['../classglow_1_1_soft_max_grad_inst.html',1,'glow']]],
  ['softmaxgradnode',['SoftMaxGradNode',['../classglow_1_1_soft_max_grad_node.html',1,'glow']]],
  ['softmaxinst',['SoftMaxInst',['../classglow_1_1_soft_max_inst.html',1,'glow']]],
  ['softmaxnode',['SoftMaxNode',['../classglow_1_1_soft_max_node.html',1,'glow']]],
  ['softmaxnodeimporter',['SoftMaxNodeImporter',['../class_soft_max_node_importer.html',1,'']]],
  ['spacetodepthinst',['SpaceToDepthInst',['../classglow_1_1_space_to_depth_inst.html',1,'glow']]],
  ['spacetodepthnode',['SpaceToDepthNode',['../classglow_1_1_space_to_depth_node.html',1,'glow']]],
  ['spacetodepthnodeimporter',['SpaceToDepthNodeImporter',['../class_space_to_depth_node_importer.html',1,'']]],
  ['sparselengthssuminst',['SparseLengthsSumInst',['../classglow_1_1_sparse_lengths_sum_inst.html',1,'glow']]],
  ['sparselengthssumnode',['SparseLengthsSumNode',['../classglow_1_1_sparse_lengths_sum_node.html',1,'glow']]],
  ['sparselengthsweightedsumgradinst',['SparseLengthsWeightedSumGradInst',['../classglow_1_1_sparse_lengths_weighted_sum_grad_inst.html',1,'glow']]],
  ['sparselengthsweightedsumgradnode',['SparseLengthsWeightedSumGradNode',['../classglow_1_1_sparse_lengths_weighted_sum_grad_node.html',1,'glow']]],
  ['sparselengthsweightedsuminst',['SparseLengthsWeightedSumInst',['../classglow_1_1_sparse_lengths_weighted_sum_inst.html',1,'glow']]],
  ['sparselengthsweightedsumnode',['SparseLengthsWeightedSumNode',['../classglow_1_1_sparse_lengths_weighted_sum_node.html',1,'glow']]],
  ['sparselengthsweightedsumoffsetsinst',['SparseLengthsWeightedSumOffsetsInst',['../classglow_1_1_sparse_lengths_weighted_sum_offsets_inst.html',1,'glow']]],
  ['sparselengthsweightedsumoffsetsnode',['SparseLengthsWeightedSumOffsetsNode',['../classglow_1_1_sparse_lengths_weighted_sum_offsets_node.html',1,'glow']]],
  ['sparsetodenseinst',['SparseToDenseInst',['../classglow_1_1_sparse_to_dense_inst.html',1,'glow']]],
  ['sparsetodensemaskinst',['SparseToDenseMaskInst',['../classglow_1_1_sparse_to_dense_mask_inst.html',1,'glow']]],
  ['sparsetodensemasknode',['SparseToDenseMaskNode',['../classglow_1_1_sparse_to_dense_mask_node.html',1,'glow']]],
  ['sparsetodensenode',['SparseToDenseNode',['../classglow_1_1_sparse_to_dense_node.html',1,'glow']]],
  ['splatinst',['SplatInst',['../classglow_1_1_splat_inst.html',1,'glow']]],
  ['splatnode',['SplatNode',['../classglow_1_1_splat_node.html',1,'glow']]],
  ['splatnodeimporter',['SplatNodeImporter',['../class_splat_node_importer.html',1,'']]],
  ['stats',['Stats',['../structglow_1_1_tensor_pool_1_1_stats.html',1,'glow::TensorPool']]],
  ['statsexporter',['StatsExporter',['../classglow_1_1_stats_exporter.html',1,'glow']]],
  ['statsexporterregistry',['StatsExporterRegistry',['../classglow_1_1_stats_exporter_registry.html',1,'glow']]],
  ['storage',['Storage',['../classglow_1_1_storage.html',1,'glow']]],
  ['strcheck',['StrCheck',['../classglow_1_1_str_check.html',1,'glow']]],
  ['subgradnode',['SubGradNode',['../classglow_1_1_sub_grad_node.html',1,'glow']]],
  ['subnode',['SubNode',['../classglow_1_1_sub_node.html',1,'glow']]],
  ['synapse',['synapse',['../structsynapse.html',1,'']]]
];
